#!/usr/bin/env zsh
# vim:ft=zsh:

rm -f $HOME/*.zwc.old(N)
rm -f $ZDOTDIR/**/*.zwc(N)
rm -f $ZDOTDIR/**/*.zwc.old(N)
rm -f $ZDOTDIR/**/.zcomp*(N)
rm -f $ZSH_CACHE_DIR/**/.zcomp*(N)
rm -f /usr/local/share/zsh/site-functions/**.zwc(N)
