#!/usr/bin/env zsh
# vim:filetype=zsh noexpandtab tabstop=8 shiftwidth=8 softtabstop=8:

rm -f $HOME/*.zwc.old(N)
rm -f $ZDOTDIR/**/*.zwc(N)
rm -f $ZDOTDIR/**/*.zwc.old(N)
rm -f $ZDOTDIR/.zcompdump
rm -f $ZSH_CACHE_DIR/.zcomp*(N)
rm -f /usr/local/share/zsh/site-functions/**.zwc(N)
