#!/usr/bin/env zsh

for i in {0..255}                                                                                                                                                                                                                                      
do
  local name=${(l:3::0:)i}
  print -P "%F{$i}color $name%f   %K{$i}   %F{232}color $name%f      %F{255}color $name%f        %k"
done
