#!/usr/bin/env zsh

# $1: space separated list of alias to release after the first load
# $2: file to source
# $3: name of the command to run after it's loaded
# $4+: argv to be passed to $3

local -a names
names=("${(@s: :)${1}}")

for name in "${names[@]}"
do
  [ "$(whence -w $name)" = "$name: alias" ] && unalias $name
done

local file_to_source="$2"
source $file_to_source

shift 2

$*
