#!/usr/bin/env zsh

# $1: space separated list of alias to release after the first load
# $2: file to source
# $3: name of the command to run after it's loaded
# $4+: argv to be passed to $3

local -a names ; names=("${(@s: :)${1}}")

unalias "${names[@]}"

. $2

shift 2

$*
