#!/usr/bin/env zsh
# vim:ft=zsh:

autoload -Uz zrecompile
compinit -d "$ZSH_CACHE_DIR/.zcompdump"

for z in .zshenv .zshrc aliases
do
	zrecompile -p $ZDOTDIR/$z
done

for z in $ZDOTDIR/functions/*(x)
do
	zrecompile -p $z
done

for z in $ZDOTDIR/completions/**/_*
do
	zrecompile -p $z
done

for z in _brew _brew_cask _brew_services _rg _git git-completion.bash _the_silver_searcher _youtube-dl _aws
do
	zrecompile -p /usr/local/share/zsh/site-functions/$z
done

rm -f $HOME/*.zwc.old(N)
rm -f $ZDOTDIR/**.zwc.old(N)
rm -f /usr/local/share/zsh/site-functions/**.zwc.old(N)
