#!/usr/bin/env zsh

autoload -Uz zrecompile
compinit -d "$ZSH_CACHE_DIR/.zcomp-$HOST"

for z in $ZDOTDIR/functions/*(x) ; zrecompile -p $z
for z in $ZDOTDIR/completions/**/_* ; zrecompile -p $z

for z in _brew _brew_cask _brew_services _rg _git git-completion.bash _the_silver_searcher _youtube-dl _aws
do
  zrecompile -p /usr/local/share/zsh/site-functions/$z
done

rm -f $HOME/*.zwc.old(N)
rm -f $ZDOTDIR/**.zwc.old(N)
rm -f /usr/local/share/zsh/site-functions/**.zwc.old(N)
