#!/usr/bin/env zsh

autoload -U zrecompile
compinit -d "$ZSH_CACHE_DIR/.zcomp-$HOST"

for z in $ZDOTDIR/functions/*(x) ; zrecompile -p $z
for z in $ZDOTDIR/completions/**/_* ; zrecompile -p $z

rm -f $HOME/*.zwc.old(N)
rm -f $ZDOTDIR/**/*.zwc.old(N)

 exec "${SHELL}"

