#!/usr/bin/env zsh
# vim:filetype=zsh noexpandtab tabstop=8 shiftwidth=8 softtabstop=8:

brew update
brew upgrade

brew cleanup
brew prune

npm update --global npm
npm update --global

rvm cleanup all

rvm get head

rvm all do gem update --system
rvm @global all do gem install neovim

pip install --upgrade pip setuptools wheel neovim pep8 flake8 autopep8 jsbeautifier

pyenv activate neovim2
pip install --upgrade pip setuptools wheel neovim pep8 flake8 autopep8 jsbeautifier

pyenv activate neovim3
pip install --upgrade pip setuptools wheel neovim pep8 flake8 autopep8 jsbeautifier

vim +PlugUpdate
