#!/usr/bin/env zsh

unset vim

export VIM="/usr/local/bin/nvim"
export VIMRUNTIME="/usr/local/share/nvim/runtime"

export EDITOR="$VIM"
export VISUAL="$VIM"
export FCEDIT="$VIM"
export SUDO_EDITOR="$VIM"
export ALTERNATE_EDITOR="$VIM"
export GEM_EDITOR="$VIM"

#if [[ "$@" =~ ':' ]]
#then
    #file_path="$(print $@ | cut -d: -f1)"
    #line_number="$(print $@ | cut -d: -f2)"
    #$VIM "+$line_number|norm! zz" "$file_path"
#else
$VIM "$@"
#fi
