#!/usr/bin/env zsh

unset vim

VIM="/usr/local/bin/nvim"
VIMRUNTIME="/usr/local/share/nvim/runtime"

if [[ "$@" =~ ':' ]]
then
    file_path="$(print $@ | cut -d: -f1)"
    line_number="$(print $@ | cut -d: -f2)"
    $VIM "+$line_number|norm! zz" "$file_path"
else
  $VIM "$@"
fi
