#!/usr/bin/env zsh

local vim="$1"

case $vim in
  (vim) echo 'use vim' ;;
  (neo) echo 'use neovim' ;;
  (mac) echo 'use macvim' ;;
  (gvim) echo 'use macvim gui' ;;
  (sys) echo 'use system vim' ;;
  (*) echo "don't know '$vim'" ;;
esac
