# Core shell/toolchain dependencies for this zsh config.

tap "romkatv/powerlevel10k"

brew "boxes"
brew "coreutils"
brew "fd"
brew "fzf"
brew "gh"
brew "jemalloc"
brew "mise"
brew "neovim"
brew "openssl@3"
brew "postgresql@17"
brew "powerlevel10k"
brew "ripgrep"
brew "tree"
brew "vivid"
brew "bat"
brew "eza"
brew "git-delta"
brew "direnv"
brew "tealdeer"
brew "atuin"
brew "lazygit"
brew "jless"
brew "fx"
brew "hyperfine"
brew "bottom"
brew "ast-grep"
brew "zoxide"
brew "fzf-tab"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "zsh-history-substring-search"
brew "zsh-autopair"
brew "zsh-you-should-use"
brew "zsh-vi-mode"

# Recommended prompt font for Powerlevel10k.
cask "font-meslo-lg-nerd-font"
