# frozen_string_literal: true

require "json"
require "stringio"
require "time"

module RubyAudit
  class ReportBuilder
    SEVERITY_EMOJI = { "High" => "🔴", "Medium" => "🟡", "Low" => "🟢", "Weak" => "⚪" }.freeze

    def initialize(detector:, results:, out_dir:)
      @detector = detector
      @results  = results
      @out_dir  = out_dir
      @ran_at   = Time.now.iso8601
      @health_score = calculate_health_score
    end

    def write_all
      write_json
      write_markdown
      write_context
      write_dashboard
      @out_dir
    end

    private

    def calculate_health_score
      score = 100.0

      # 1. Security (Heavy: -20 per CVE, -15 per High, -5 per Medium)
      score -= vuln_count * 20
      score -= brakeman_by_confidence("High").length * 15
      score -= brakeman_by_confidence("Medium").length * 5

      # 2. Complexity (Moderate: -2 per hotspot >= 30, -5 if any > 100)
      hotspots = @results.dig(:flog, :high_complexity) || []
      score -= hotspots.length * 2
      score -= 5 if hotspots.any? { |h| h[:score] > 100 }

      # 3. Duplication (Moderate: -1 per mass >= 50)
      duplicates = @results.dig(:flay, :output) || []
      score -= duplicates.count { |d| d[:mass] >= 50 }

      # 4. Smells & Style (Light: -0.5 per smell, -0.1 per cop)
      score -= (@results.dig(:reek, :output)&.length.to_i * 0.5)
      score -= (@results.dig(:rubocop, :summary, "offense_count").to_i * 0.1)

      [score, 0.0].max.round(1)
    end

    def write_dashboard
      File.write(File.join(@out_dir, "dashboard.txt"), dashboard)
    end

    def dashboard
      io = StringIO.new
      border = "━" * 60
      io.puts "\e[1m#{border}\e[0m"
      io.puts "\e[1m  RUBY METRICS DASHBOARD\e[0m"
      io.puts "\e[1m#{border}\e[0m"
      io.puts "  Target:  #{@detector.root}"
      io.puts "  Date:    #{@ran_at}"
      io.puts ""

      color = case @health_score
              when 90..100 then "\e[32m" # Green
              when 70..89  then "\e[33m" # Yellow
              else              "\e[31m" # Red
              end

      io.puts "  \e[1mPlatform Health Score:\e[0m  #{color}#{@health_score}/100\e[0m"
      io.puts ""

      io.puts "  \e[1mCORE METRICS\e[0m"
      score_rows.each do |label, count, status|
        printf(io, "  %-25s %4d  %s\n", label, count, status)
      end

      io.puts ""
      io.puts "  \e[1mHOTSPOTS\e[0m"
      hotspots = @results.dig(:flog, :high_complexity) || []
      if hotspots.any?
        hotspots.first(3).each { |h| printf(io, "  ⚠️  %-35s %5.1f\n", h[:method][0..34], h[:score]) }
      else
        io.puts "  ✅ No significant complexity hotspots."
      end

      io.puts ""
      io.puts "\e[1m#{border}\e[0m"
      io.string
    end

    def write_json
      File.write(File.join(@out_dir, "summary.json"), JSON.pretty_generate(summary_hash))
    end

    def write_markdown
      File.write(File.join(@out_dir, "report.md"), markdown)
    end

    def write_context
      File.write(File.join(@out_dir, "context.md"), ai_context)
    end

    def summary_hash
      {
        generated_at: @ran_at,
        health_score: @health_score,
        target: @detector.root.to_s,
        versions: @detector.summary,
        scores: {
          security_vulns: vuln_count,
          brakeman_high: brakeman_by_confidence("High").length,
          brakeman_medium: brakeman_by_confidence("Medium").length,
          rubocop_offenses: @results.dig(:rubocop, :summary, "offense_count").to_i,
          reek_smells: @results.dig(:reek, :output)&.length.to_i,
          flog_hotspots: @results.dig(:flog, :high_complexity)&.length.to_i,
          flay_duplicates: @results.dig(:flay, :output)&.length.to_i
        },
        results: @results.transform_values { |r| r&.except(:raw) }
      }
    end

    def markdown
      io = StringIO.new
      io.puts "# Ruby Audit Report"
      io.puts ""
      io.puts "**Target:** `#{@detector.root}`  "
      io.puts "**Generated:** #{@ran_at}  "
      io.puts "**Ruby:** #{@detector.ruby_version}  "
      io.puts "**Rails:** #{@detector.rails_version || 'n/a'}  "
      io.puts "**Framework:** #{@detector.framework}"
      io.puts ""

      io.puts "## Summary"
      io.puts ""
      io.puts "| Check | Count | Status |"
      io.puts "|-------|------:|--------|"
      score_rows.each { |row| io.puts "| #{row.join(' | ')} |" }
      io.puts ""

      section_bundler_audit(io)
      section_brakeman(io)
      section_rubocop(io)
      section_reek(io)
      section_flog(io)
      section_flay(io)

      io.string
    end

    def ai_context
      io = StringIO.new
      io.puts "# Codebase Analysis Context"
      io.puts ""
      io.puts "This file was generated by ruby-audit for use as AI context."
      io.puts "It summarizes static analysis findings. Use it alongside the source context"
      io.puts "to answer questions about this codebase."
      io.puts ""
      io.puts "## Versions"
      io.puts "- Ruby: #{@detector.ruby_version}"
      io.puts "- Rails: #{@detector.rails_version || 'not used'}"
      io.puts "- Framework: #{@detector.framework}"
      io.puts ""
      io.puts "## Key Findings"
      io.puts ""

      # CVEs
      vulns = @results.dig(:bundler_audit, :output) || []
      if vulns.any?
        io.puts "### Security Vulnerabilities (#{vulns.length})"
        vulns.each { |v| io.puts "- **#{v['advisory']['id']}** in `#{v['gem']['name']}` #{v['gem']['version']}: #{v['advisory']['title']}" }
        io.puts ""
      end

      # Brakeman high/medium
      warnings = @results.dig(:brakeman, :output) || []
      high_med = warnings.select { |w| %w[High Medium].include?(w["confidence"]) }
      if high_med.any?
        io.puts "### Brakeman High/Medium Warnings (#{high_med.length})"
        high_med.each { |w| io.puts "- **#{w['warning_type']}** in `#{w['file']}:#{w['line']}` [#{w['confidence']}]: #{w['message']}" }
        io.puts ""
      end

      # Top complexity hotspots
      hotspots = @results.dig(:flog, :high_complexity) || []
      if hotspots.any?
        io.puts "### Complexity Hotspots (score ≥ 30)"
        hotspots.first(10).each { |h| io.puts "- `#{h[:method]}` — score #{h[:score]}" }
        io.puts ""
      end

      # Top smells
      smells = @results.dig(:reek, :output) || []
      if smells.any?
        by_type = smells.group_by { |s| s["smell_type"] }.sort_by { |_, v| -v.length }
        io.puts "### Code Smells by Type"
        by_type.first(8).each { |type, instances| io.puts "- **#{type}**: #{instances.length}" }
        io.puts ""
      end

      io.puts "## Metrics"
      io.puts "- RuboCop offenses: #{@results.dig(:rubocop, :summary, 'offense_count').to_i}"
      io.puts "- Reek smells: #{smells.length}"
      io.puts "- Flog hotspots (≥30): #{hotspots.length}"
      io.puts "- Flay duplications: #{(@results.dig(:flay, :output) || []).length}"
      io.puts ""

      io.string
    end

    # ── section renderers ────────────────────────────────────────────────────

    def section_bundler_audit(io)
      r = @results[:bundler_audit]
      return unless r

      io.puts "## Dependency Vulnerabilities (bundler-audit)"
      io.puts ""
      if r[:skipped]
        io.puts "_Skipped: #{r[:skipped]}_"
      elsif (vulns = r[:output] || []).empty?
        io.puts "No known vulnerabilities found."
      else
        vulns.each do |v|
          gem  = v["gem"]
          adv  = v["advisory"]
          io.puts "- **#{adv['id']}** `#{gem['name']} #{gem['version']}` — #{adv['title']} *(#{adv['cvss_v3'] || adv['cvss_v2'] || 'no score'})*"
        end
      end
      io.puts ""
    end

    def section_brakeman(io)
      r = @results[:brakeman]
      return unless r

      io.puts "## Security Warnings (brakeman)"
      io.puts ""
      if r[:skipped]
        io.puts "_Skipped: #{r[:skipped]}_"
        io.puts ""
        return
      end
      warnings = r[:output] || []
      if warnings.empty?
        io.puts "No warnings found."
      else
        %w[High Medium Low Weak].each do |conf|
          group = brakeman_by_confidence(conf)
          next if group.empty?

          io.puts "### #{SEVERITY_EMOJI[conf] || ''} #{conf} (#{group.length})"
          group.each { |w| io.puts "- `#{w['file']}:#{w['line']}` **#{w['warning_type']}** — #{w['message']}" }
          io.puts ""
        end
      end
    end

    def section_rubocop(io)
      r = @results[:rubocop]
      return unless r

      io.puts "## Style & Complexity (rubocop)"
      io.puts ""
      sum = r[:summary] || {}
      io.puts "Files inspected: #{sum['inspected_file_count'].to_i} · Offenses: #{sum['offense_count'].to_i}"
      io.puts ""
      by_cop = (r[:output] || []).group_by { |o| o["cop_name"] }.sort_by { |_, v| -v.length }.first(15)
      by_cop.each do |cop, offenses|
        io.puts "- **#{cop}** (#{offenses.length})"
      end
      io.puts ""
    end

    def section_reek(io)
      r = @results[:reek]
      return unless r

      io.puts "## Code Smells (reek)"
      io.puts ""
      smells = r[:output] || []
      if smells.empty?
        io.puts "No smells detected."
      else
        by_type = smells.group_by { |s| s["smell_type"] }.sort_by { |_, v| -v.length }
        by_type.first(12).each do |type, instances|
          io.puts "- **#{type}** (#{instances.length}): #{instances.first(2).map { |i| "`#{i['context']}`" }.join(', ')}"
        end
      end
      io.puts ""
    end

    def section_flog(io)
      r = @results[:flog]
      return unless r

      io.puts "## Complexity Hotspots (flog ≥ 30)"
      io.puts ""
      hotspots = r[:high_complexity] || []
      if hotspots.empty?
        io.puts "No methods exceed complexity threshold."
      else
        hotspots.first(20).each { |h| io.puts "- `#{h[:method]}` — #{h[:score]}" }
      end
      io.puts ""
    end

    def section_flay(io)
      r = @results[:flay]
      return unless r

      io.puts "## Code Duplication (flay)"
      io.puts ""
      matches = r[:output] || []
      if matches.empty?
        io.puts "No significant duplication found."
      else
        matches.first(10).each do |m|
          io.puts "- Mass #{m[:mass]}: #{m[:locations].map { |l| "`#{l[:file]}:#{l[:line]}`" }.join(', ')}"
        end
      end
      io.puts ""
    end

    # ── helpers ───────────────────────────────────────────────────────────────

    def vuln_count
      (@results.dig(:bundler_audit, :output) || []).length
    end

    def brakeman_by_confidence(conf)
      (@results.dig(:brakeman, :output) || []).select { |w| w["confidence"] == conf }
    end

    def score_rows
      [
        ["Dependency CVEs (bundler-audit)", vuln_count, vuln_count.zero? ? "✅" : "🔴"],
        ["Brakeman High",   brakeman_by_confidence("High").length,   brakeman_by_confidence("High").empty?   ? "✅" : "🔴"],
        ["Brakeman Medium", brakeman_by_confidence("Medium").length, brakeman_by_confidence("Medium").empty? ? "✅" : "🟡"],
        ["RuboCop offenses", @results.dig(:rubocop, :summary, "offense_count").to_i, "ℹ️"],
        ["Reek smells",    @results.dig(:reek, :output)&.length.to_i,          "ℹ️"],
        ["Flog hotspots",  @results.dig(:flog, :high_complexity)&.length.to_i, "ℹ️"],
        ["Flay duplicates", @results.dig(:flay, :output)&.length.to_i, "ℹ️"]
      ]
    end
  end
end
