# vim:set filetype=zsh expandtab shiftwidth=2 textwidth=64:

# hash -d vim=$HOME/dotfiles/vim
# hash -d zsh=$HOME/dotfiles/zsh
hash -d api="$HOME/wmx/bp/v2"
hash -d assets="$HOME/wmx/bp/assets"
hash -d bp="$HOME/wmx/bp"
hash -d course_publisher="$HOME/wmx/bp/course-publisher"
hash -d dotfiles="$HOME/dotfiles"
hash -d instructor_dashboard="$HOME/wmx/bp/instructor-dashboard"
hash -d marketing_admin="$HOME/wmx/bp/marketing-admin"
hash -d marketing="$HOME/wmx/bp/marketing"
hash -d reporting_api="$HOME/wmx/bp/reporting-api"
hash -d s3="$HOME/wmx/s3"
hash -d src="$HOME/src"
hash -d sso="$HOME/wmx/bp/sso"
hash -d teachers="$HOME/wmx/bp/teachers"
hash -d tenant_dashboard="$HOME/wmx/bp/tenant-dashboard"
hash -d user_manager="$HOME/wmx/bp/user-manager"
hash -d web="$HOME/wmx/bp/webapp"
hash -d wikis="$HOME/wmx/wikis"
hash -d wmx="$HOME/wmx"
hash -d download="$HOME/Downloads"
hash -d pictures="$HOME/Pictures"
hash -d documents="$HOME/Documents"
hash -d dbx="$HOME/Dropbox/mike"
hash -d zdots="$ZDOTDIR"
