# Kanagawa Wave — shell colors. GENERATED by zdots-theme-gen from
# etc/themes/kanagawa-wave.yaml. Do not edit by hand; edit the source + regenerate.
export ZDOTS_FZF_COLORS='--color=fg:#DCD7BA,bg:#1A1B2F,hl:#7E9CD8,fg+:#DCD7BA,bg+:#2D4F67,hl+:#7FB4CA,info:#E6C384,prompt:#98BB6C,pointer:#D27E99,marker:#D27E99,spinner:#E6C384,header:#957FB8,border:#54546D'
export LSCOLORS='ExGxDxGxGxegedabagacad'
