#!/usr/bin/env zsh

bytesToHuman () {
  local b=${1:-0}
  local d=''
  local s=0
  local S=(Bytes {K,M,G,T,E,P,Y,Z}iB)

  while ((b > 1024))
  do
    d="$(printf ".%02d" $((b % 1024 * 100 / 1024)))"
    b=$((b / 1024))

    let s++
  done

  echo "$b$d ${S[$s]} of space was cleaned up :3"
}

# Ask for the administrator password upfront
if [ "$EUID" -ne 0  ]
then
  echo "Please run as root"
  exit
fi

local oldAvailable=$(df / | tail -1 | awk '{print $4}')

# rvm system gem cleanup
# rvm cleanup all
#
echo "Delete all Zsh cache files"
sudo rm -f $HOME/**.{zwc,zwc.old}(N)
sudo rm -f /usr/local/**.{zwc,zwc.old}(N)

sudo rm -rf $HOME/**/.zcomp*(N)
sudo rm -rf /usr/local/**/.zcomp*(N)

echo "Restart DNS services"
sudo killall -HUP mDNSResponder

echo "Run all period maintenance scripts"
sudo periodic all

echo 'Kill all .DS_Store files on all mounted volumes'
sudo rm -f /**/.DS_Store(N)

echo 'Empty the Trash on all mounted volumes and the main HDD...'
sudo rm -rfv /**/.Trashes

echo 'Clear System Log Files...'
# if exists --> sudo rm -rfv /private/var/log/asl/*.asl
# if exists --> sudo rm -rfv /Library/Logs/DiagnosticReports/*
# if exists --> sudo rm -rfv /Library/Logs/Adobe/*
# if exists --> rm -rfv $HOME/Library/Containers/com.apple.mail/Data/Library/Logs/Mail/*
# if exists --> rm -rfv $HOME/Library/Logs/CoreSimulator/*

echo 'Clear Adobe Cache Files...'
# if exists --> sudo rm -rfv "$HOME/Library/Application Support/Adobe/Common/Media Cache Files/*"

echo 'Cleanup iOS Applications...'
# if exists --> rm -rfv $HOME/Music/iTunes/iTunes\ Media/Mobile\ Applications/*

echo 'Remove iOS Device Backups...'
# if exists --> rm -rfv $HOME/Library/Application\ Support/MobileSync/Backup/*

echo 'Cleanup XCode Derived Data and Archives...'
# if exists --> rm -rfv $HOME/Library/Developer/Xcode/DerivedData/* 
# if exists --> rm -rfv $HOME/Library/Developer/Xcode/Archives/* 

echo 'Cleanup Homebrew Cache...'
brew cleanup --force -s
brew cask cleanup
# if exists --> rm -rfv /Library/Caches/Homebrew/*
brew tap --repair

echo 'Cleanup any old versions of system gems'
rvm system do gem cleanup

echo "Truncate local application logs"
sudo gtruncate -s 0  /usr/local/**.log

echo "Truncate development logs"
sudo gtruncate -s 0  $HOME/bp/**.log

echo 'Purge inactive memory...'
sudo purge


done

clear && echo 'Success!'

local newAvailable=$(df / | tail -1 | awk '{print $4}')
local count=$((newAvailable-oldAvailable))
count=$(($count * 512))

bytesToHuman $count
