#!/usr/bin/env zsh
# vim:ft=zsh:

echo
echo "Before:"
echo
du -h .git | tail -1
echo
git show-ref -s HEAD > .git/shallow
git reflog expire --expire=0
git prune
git prune-packed
git gc --aggressive
echo "After:"
echo
du -h .git | tail -1
echo
echo
