# assets/dracula/p10k-overrides.zsh
# This file contains user-owned color overrides for Powerlevel10k.
# These will be loaded AFTER the main p10k.zsh to ensure they take precedence.

# OS Icon
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=255

# Prompt Character (Success/Error colors)
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=84
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=196

# Directory Colors
typeset -g POWERLEVEL9K_DIR_FOREGROUND=0
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=0
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=0

# Status Colors
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=2
typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=2
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=3
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=3
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=3

# Kubecontext Colors
typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_FOREGROUND=7
typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_BACKGROUND=5

# Command Execution Time
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=0

# AI/Runtime Environments (Mise/ASDF)
typeset -g POWERLEVEL9K_ASDF_FOREGROUND=0
typeset -g POWERLEVEL9K_DIRENV_FOREGROUND=3
