#!/usr/bin/env zsh

local cache=$ZSH_CACHE_DIR
autoload -U compinit zrecompile
compinit -d "$cache/zcomp-$HOST"

for f in "$ZDOTDIR/.zshrc" "$cache/zcomp-$HOST"
do
  zrecompile -p $f && command rm -f $f.zwc.old
done

source "$ZDOTDIR/.zshrc"
