#!/usr/bin/env zsh
# vim:ft=zsh

# TODO: What directories are *not* in the doots.lst?

mkdir -p "$HOME/dooty/doots"
mkdir -p "$XDG_CACHE_HOME/dooty"

local dootcat="$1"

# dootify colorschemes
# dootify emacs
# dootify tmux
# dootify bash
# dootify fish

local -i step=1
local -a buffer

if [[ "$dootcat" == 'all' ]]; then
  dootify zsh
  dootify dotfiles
  dootify vim
else
  while read doot; do
    echo 

    a=("${(@s|/|)doot}")

    org="$a[1]"
    repo="$a[2]"

    # {{{ Async
    # buffer+="zsh -c 'gdoot $dootcat $org $repo'"

    # if ((step > 3)); then
    #   echo
    #   parallel -j3 -- $buffer[0] $buffer[1] $buffer[2]

    #   step=1
    #   unset buffer
    #   typeset -a buffer
    # else
    #   step=$((step+1))
    # fi
    # echo $buffer
    # echo "[$step] gdoot $dootcat $org $repo"
    # }}}

    gdoot $dootcat $org $repo
  done < <(cat "$XDG_CONFIG_HOME/dooty/doots.${dootcat}.lst")
fi
