#!/usr/bin/env zsh

# https://zsh.sourceforge.io/Doc/Release/Shell-Grammar.html

local option="$1"

[[ ! -z "$OMFPATH" ]] && mkdir -p "$OMFPATH"

[[ ! -a "$OMFPATH/.omfrc" ]] && touch "$OMFPATH/.omfrc"

if [ -z "$option" ]; then
  cd "$OMFPATH"
  return 0
fi

case "$option" in
  (fe) ;&
  (fr*)
    [[ ! -z "$OMFPATH/springleaf/frontend/" ]] && mkdir -p "$OMFPATH/springleaf/frontend/"
    cd "$OMFPATH/springleaf/frontend/"
    # open https://github.com/springleaf/frontend/pulls
    ;;

  (mu*)
    [[ ! -z "$OMFPATH/springleaf/mulesoft_client/" ]] && mkdir -p "$OMFPATH/springleaf/mulesoft_client/"
    cd "$OMFPATH/springleaf/mulesoft_client/"
    # open https://github.com/springleaf/mulesoft_client/pulls
    ;;

  (ac*)
    [[ ! -z "$OMFPATH/springleaf/acquisition/" ]] && mkdir -p "$OMFPATH/springleaf/acquisition/"
    cd "$OMFPATH/springleaf/acquisition/"
    # open https://github.com/springleaf/acquisition/pulls
    ;;

  (bun*) ;&
  (bbi)
    omf-all-do 'bundle check || bundle install'
    ;;

  (bbu)
    omf-all-do 'bundle update'
    ;;

  (ppi)
    omf-all-do 'pip install -r requirements.txt'
    ;;

  (ppu)
    omf-all-do 'pip install -U -r requirements.txt'
    ;;

  (fet*) ;&
  (gfa)
    omf-all-do 'git fetch --all --prune --verbose'
    ;;

  (gbr)
    omf-all-do 'git rev-parse --abbrev-ref head'
    ;;

  (ggc)
    omf-all-do 'git gc --aggressive'
    ;;

  (pull) ;&
  (gpu)
    omf-all-do 'git pull --rebase --autostash'
    ;;

  (stat*) ;&
  (gss)
    omf-all-do 'git status --short'
    ;;

  (rc)
    [[ ! -a "$OMFPATH/.omfrc" ]] && touch "$OMFPATH/.omfrc"
    cat "$OMFPATH/.omfrc"
    ;;
  (*) echo
    echo "No args will \`cd\` to the $OMFPATH."
    echo
    echo "frontend        => cd \"$OMFPATH/springleaf/frontend/\""
    echo "acquisition     => cd \"$OMFPATH/springleaf/acquisition/\""
    echo "mulesoft_client => cd \"$OMFPATH/springleaf/mulesoft_client/\""
    echo "bundle          => omf-all-do 'bundle check || bundle install' "
    echo "fetch           => omf-all-do 'git fetch --all --prune --verbose' "
    echo "status          => omf-all-do 'git status --short'"
    echo "bbi             => omf-all-do 'bundle check || bundle install' "
    echo "bbu             => omf-all-do 'bundle update' "
    echo "ppi             => omf-all-do 'pip install -r requirements.txt' "
    echo "ppu             => omf-all-do 'pip install -U -r requirements.txt' "
    echo "gfa             => omf-all-do 'git fetch --all --prune --verbose' "
    echo "gbr             => omf-all-do 'git rev-parse --abbrev-ref head' "
    echo "ggc             => omf-all-do 'git gc --aggressive' "
    echo "gpu             => omf-all-do 'git pull --rebase --autostash' "
    echo "gss             => omf-all-do 'git status --short'"
    echo "rc              => cat \"$OMFPATH/.omrc\""

    echo
    echo "I don't know what to do with: '$@'"
    echo

    return 1
    ;;
esac

return 0
