#!/usr/bin/env zsh

if [[ ! -z "~omf" ]]; then 
  mkdir -p ~omf
fi

if [[ ! -z "$OMFPATH" ]]; then 
  mkdir -p "$OMFPATH"
fi

if [[ ! -a "$OMFPATH/.omfrc" ]]; then 
  touch "$OMFPATH/.omfrc"
fi

if [[ ! -z "$HOME/.local/share/omf-all-do/" ]]; then 
  mkdir -p "$HOME/.local/share/omf-all-do/"
fi

echo "$(iso8601-local) ; $@" >>! "$HOME/.local/share/omf-all-do/history"

# for directory in $HOME/omf/*/
while read directory ; do
  local repo="$directory"
  cd "$OMFPATH/$directory"

  local segment_repo='%F{8}[%f%F{11}REPO%f%F{8}=%f%B$repo%b%F{8}]%f'
  local segment_branch='%F{8}[%f%F{11}BRANCH%f%F{8}=%f%B$(git rev-parse --abbrev-ref HEAD)%b%F{8}]%f'
  local segment_cmd='%F{8}[%f%F{11}CMD%f%F{8}=%f%B$@%b%F{8}]%f'

  print -P "$segment_repo $segment_branch $segment_cmd\n"

  eval "$@"

  cd "$OMFPATH"
  echo
done < "$OMFPATH/.omfrc"

return 0
