#!/usr/bin/env zsh

local option="$1"

if [ -z "$option" ]
then
  cd ~sk
  return 0
fi

case "$option" in
  (aff) cd "$SKPATH/nats/affiliate-tracking" ;;
  (app) if [[ "$2" == 'admin' ]]
    then
      cd "$SKPATH/mr-skin/mr-skin-rails/engines/mrskin_admin"
    else
      cd "$SKPATH/mr-skin/mr-skin-rails"
    fi ;;
  (auth) if [[ "$2" == 'client' ]]
    then
      cd "$SKPATH/sk-auth/sk-auth-client"
    else
      cd "$SKPATH/sk-auth/sk-auth-app"
    fi ;;
  (billing) if [[ "$2" == 'client' ]]
    then
      cd "$SKPATH/sk-billing/sk-billing-client"
    else
      cd "$SKPATH/sk-billing/sk-billing-app"
    fi ;;
  (branches) sk-all-do 'git rev-parse --abbrev-ref head' ;;
  (bundle) sk-all-do 'bundle check || bundle install' ;;
  (docs) cd "$SKPATH/external/sk-developer-network" ;;
  (email) cd "$SKPATH/customer-email-system/core" ;;
  (fetch) sk-all-do 'git fetch --all --prune --verbose' ;;
  (files) cd $HOME/Dropbox/mike/SK ;;
  (gems) cd "$SKPATH/gems" ;;
  (ggc) sk-all-do 'git gc --aggressive' ;;
  (gpm) cd "$SKPATH/good-parts-media/prep-service" ;;
  (help) print "No args will \`cd\` to the $SKPATH." ;;
  (prep) cd "$SKPATH/good-parts-media/prep-service" ;;
  (pull) sk-all-do 'git pull --rebase --autostash' ;;
  (puppet) cd "$SKPATH/puppet" ;;
  (reports) cd "$SKPATH/stats/report-track" ;;
  (stats) cd "$SKPATH/stats/report-track" ;;
  (status) sk-all-do 'git status --short' ;;
  (tickets) cd "$SKPATH/internal-admins/tickets" ;;
  (trans) cd "$SKPATH/internal-admins/sk_translations_admin" ;;
  (vu) cd "$SKPATH/web-applications/vitaly-uncensored" ;;
  (*) echo
    echo "aff      => cd \"$SKPATH/nats/affiliate-tracking\""
    echo "app      => cd \"$SKPATH/mr-skin/mr-skin-rails\""
    echo "auth     => cd \"$SKPATH/sk-auth/sk-auth-app\""
    echo "billing  => cd \"$SKPATH/sk-billing/sk-billing-app\""
    echo "branches => sk-all-do 'git rev-parse --abbrev-ref head'"
    echo "bundle   => sk-all-do 'bundle check || bundle install'"
    echo "docs     => cd \"$SKPATH/external/sk-developer-network\""
    echo "email    => cd \"$SKPATH/customer-email-system/core\""
    echo "fetch    => sk-all-do 'git fetch --all --prune --verbose'"
    echo "files    => cd $HOME/Dropbox/mike/SK"
    echo "gems     => cd \"$SKPATH/gems\""
    echo "ggc      => sk-all-do 'git gc --aggressive'"
    echo "gpm      => cd \"$SKPATH/good-parts-media/prep-service\""
    echo "help     => print \"No args will \`cd\` to the $SKPATH.\""
    echo "prep     => cd \"$SKPATH/good-parts-media/prep-service\""
    echo "pull     => sk-all-do 'git pull --rebase --autostash'"
    echo "puppet   => cd \"$SKPATH/puppet\""
    echo "reports  => cd \"$SKPATH/stats/report-track\""
    echo "stats    => cd \"$SKPATH/stats/report-track\""
    echo "status   => sk-all-do 'git status --short'"
    echo "tickets  => cd \"$SKPATH/internal-admins/tickets\""
    echo "trans    => cd \"$SKPATH/internal-admins/sk_translations_admin\""
    echo "vu       => cd \"$SKPATH/web-applications/vitaly-uncensored\""
    echo
    echo "I don't know what to do with: '$@'"
    echo
    sk help
    return 1 ;;
esac

return 0

