#!/usr/bin/env zsh

message () {
  local text="$1"
  echo
  echo " $text" | /usr/local/bin/boxes -d shell
  echo
}

message 'UPGRADE START'

message 'HOMEBREW'
upgrade-homebrew

# message 'MACOS'
# upgrade-macos
# 
# message 'VIM PLUGINS'
# upgrade-vim
# 
# message 'RUBY'
# upgrade-ruby
# 
# message 'PIP3'
# upgrade-pip3
# 
# message 'NPM' 
# upgrade-npm
# 
# message 'CABAL'
# upgrade-cabal
# 
# message 'PIP2'
# upgrade-pip2

message 'ANTIGEN'
upgrade-antigen

message 'UPGRADE DONE' 

