#!/usr/bin/env zsh

set -euo pipefail

GOLANG_VERSION="${ASDF_GOLANG_VERSION:-latest:1.24}"
NEOVIM_VERSION="${ASDF_NEOVIM_VERSION:-latest:0.11}"
NODEJS_VERSION="${ASDF_NODEJS_VERSION:-latest:24}"
PYTHON_VERSION="${ASDF_PYTHON_VERSION:-latest:3.10}"
RUBY_VERSION="${ASDF_RUBY_VERSION:-latest:3.4}"
UPDATE_GLOBALS="${ZDOTS_UPGRADE_GLOBALS:-0}"
DRY_RUN="${ZDOTS_UPGRADE_DRY_RUN:-0}"

run_cmd() {
  print -r -- "+ $*"
  if [[ "$DRY_RUN" == "1" ]]; then
    return 0
  fi
  "$@"
}

ensure_plugin() {
  local tool="$1"
  if ! asdf plugin list | grep -qx "$tool"; then
    run_cmd asdf plugin add "$tool"
  fi
}

install_track() {
  local tool="$1"
  local version="$2"
  ensure_plugin "$tool"
  run_cmd asdf install "$tool" "$version"
  run_cmd asdf set --home "$tool" "$version"
}

# asdf update --head
run_cmd asdf plugin update --all

# asdf plugin add nim
# asdf install nim latest
# asdf set --home nim latest

# asdf plugin add julia
# asdf install julia latest
# asdf set --home julia latest

install_track golang "$GOLANG_VERSION"
install_track neovim "$NEOVIM_VERSION"
install_track nodejs "$NODEJS_VERSION"
install_track python "$PYTHON_VERSION"
install_track ruby "$RUBY_VERSION"

# asdf plugin add yarn
# asdf install yarn latest
# asdf set --home yarn latest

if [[ "$UPDATE_GLOBALS" == "1" ]]; then
  run_cmd pip3 install -U pip
  run_cmd touch ~/.default-python-packages
  # pip3 install -U -r ~/.default-python-packages

  run_cmd npm update -g npm
  run_cmd npm update -g neovim
  run_cmd npm update -g

  run_cmd gem update --system
  run_cmd gem install bundler
  run_cmd gem install neovim
  run_cmd gem update
fi

run_cmd asdf reshim
