#!/usr/bin/env zsh

message () {
  local text="$1"
  local boxes_bin
  boxes_bin="$(command -v boxes 2>/dev/null)"
  echo
  if [[ -n "$boxes_bin" ]]; then
    echo " $text" | "$boxes_bin" -d shell
  else
    echo "[$text]"
  fi
  echo
}

message 'UPGRADE START'

message 'HOMEBREW'
upgrade-homebrew

message 'MISE'
upgrade-mise

# message 'MACOS'
# upgrade-macos
#
# message 'VIM PLUGINS'
# upgrade-vim
#
# message 'RUBY'
# upgrade-ruby
#
# message 'PIP3'
# upgrade-pip3
#
# message 'NPM'
# upgrade-npm
#
# message 'CABAL'
# upgrade-cabal
#
# message 'PIP2'
# upgrade-pip2

message 'UPGRADE DONE'
