#!/usr/bin/env zsh

brew update --verbose
brew update --auto-update --verbose

brew upgrade --greedy --force --verbose

if [[ -f "$ZDOTDIR/Brewfile" ]]; then
  brew bundle check --file "$ZDOTDIR/Brewfile" || brew bundle --file "$ZDOTDIR/Brewfile"
fi

cleanup-homebrew
