#!/usr/bin/env zsh

local option="$1"

if [ -z "$option" ]
then
  cd ~w3r
  return 0
fi

case "$option" in
  (br*) w3r-all-do 'git rev-parse --abbrev-ref head' ;;
  (bu*) w3r-all-do 'bundle check || bundle install' ;;
  (co*) cd "$W3RPATH/core" ;;
  (da*) cd "$W3RPATH/dashboard" ;;
  (dr*) cd $HOME/Dropbox/mike/projects/wwworkremote/ ;;
  (fe*) w3r-all-do 'git fetch --all --prune --verbose' ;;
  (gg*) w3r-all-do 'git gc --aggressive' ;;
  (gs*) w3r-all-do 'git status --short' ;;
  (pu*) w3r-all-do 'git pull --rebase --autostash' ;;
  (rc) cat "$W3RPATH/.w3rrc" ;;
  (*) echo
    echo "No args will \`cd\` to the $W3RPATH."
    echo
    echo "core      => cd \"$W3RPATH/core/\""
    echo "dashboard => cd \"$W3RPATH/dashboard/\""
    echo "branches  => w3r-all-do 'git rev-parse --abbrev-ref head'"
    echo "bundle    => w3r-all-do 'bundle check || bundle install'"
    echo "dropbox   => cd $HOME/Dropbox/mike/projects/wwworkremote/"
    echo "fetch     => w3r-all-do 'git fetch --all --prune --verbose'"
    echo "ggc       => w3r-all-do 'git gc --aggressive'"
    echo "pull      => w3r-all-do 'git pull --rebase --autostash'"
    echo "status    => w3r-all-do 'git status --short'"
    echo
    echo "I don't know what to do with: '$@'"
    echo
    return 1 ;;
esac

return 0


